name: Node.js CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run build --if-present
    
    # New steps to demonstrate output
    - name: Print a message
      run: echo "This is a demonstration of GitHub Actions!"

    - name: Start server and output logs
      run: |
        node server.js &
        sleep 5
        curl http://127.0.0.1:3000
    
    - name: List files in directory
      run: ls -alh

    - name: Show environment variables
      run: printenv

    - run: npm test || echo "No tests available, skipping test step."